apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
    - name : my-pod
      image: nginx
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: my-vars
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-sec
              key: DB_PASSWORD
