apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
    - image: nginx
      env:
        - name: MYSQL_USER
          valuesFrom:
            configMapKeyRef:
              name: my-vars
              key: DB_USER
        - name: MYSQL_PASSWORD
          valuesFrom:
            secretKeyRef:
              name: my-sec
              key: DB_PASSWORD
