apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: my-deployment
spec:
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: my-app
          image: nginx
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-vars
                  key: DB_PASSWORD
            - name: MYSQL_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-vars
                  key: DB_USER
              #Secret FIle
              #- name: MYSQL_USER_NAME
              #valueFrom:
               # secretKeyRef:
                #  name: my-sec
                 # key: DB_USER
  replicas: 4
  selector:
    matchLabels:
      app: student-app
  strategy:
    type: RollingUpdate
