---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  Labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: nginx
      ports:
        - name : my-http
          protocol: TCP
          containerPort: 80 
...

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports: 
    -name: my-http
     protocol: TCP
     containerPort: 80

    -name: my-http
     protocol: TCP
     containerPort: 80
...