apiVersion: apps/v1
kind: RepicaSet
metadata:
  name: my-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-pod-container
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [ xyz-app, cbz-app]}