apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cbz-app
    spec:
      containers:
        - name: my-pod-container-1
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [ xyz-app, cbz-app]}