apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      name: http
      port: 80      #clusterIp Port 
      targetPort: 80  #container Port

    - protocol: TCP
      name: java
      port: 8080
      targetPort: 8080