apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      name: http
      port: 8080     #clusterIp Port 
      targetPort: 8080  #container Port
