apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: clusterIP
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      name: http
      port: 80      #clusterIp Port 
      targetPort: 80  #container Port
