apiVersion: v1
kind: PersistentVolume
metadata:
  name: cbz-pv
spec:
  capacity:
    storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /mnt/data