apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbz-pvc
spec:
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard