apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }} #cbz-app-home
spec:
  type: {{ .Values.spec.type}} #LoadBalancer
  selector:
    app: {{ .Values.app.name }} #cbz-app-home
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.port}} #80      #clusterIp Port 
      targetPort: {{ .Values.port}} #80  #container Port
