apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cbz-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: cbz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cbz-app-home
            port:
              number: 80

